title: OMNeT++ Discrete Event Simulator
author: OMNeT++ Dev Team
email: omnetpp@googlegroups.com

twitter_username: omnetpp
github_username:  omnetpp
excerpt_separator: <!--more-->
google_analytics: UA-240922-2

sass:
    style: compressed

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
plugins:
    - jekyll-paginate
    - jekyll-redirect-from
